ALTER TABLE "Route" ADD COLUMN "startAddress" TEXT;
ALTER TABLE "Route" ADD COLUMN "startLatitude" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN "startLongitude" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN "finishAddress" TEXT;
ALTER TABLE "Route" ADD COLUMN "finishLatitude" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN "finishLongitude" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN "plannedStartTime" TEXT NOT NULL DEFAULT '05:00';
ALTER TABLE "Route" ADD COLUMN "timePerDropMinutes" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Route" ADD COLUMN "customerSlotMinutes" INTEGER NOT NULL DEFAULT 60;
