-- Defensive migration for live Railway database drift.
-- These columns are read by the route list, route detail and driver route flows.

ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "driverAccessToken" TEXT;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "driverAccessTokenCreatedAt" TIMESTAMP(3);
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "driverRouteLinkSentAt" TIMESTAMP(3);
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "startAddress" TEXT;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "startLatitude" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "startLongitude" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "finishAddress" TEXT;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "finishLatitude" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "finishLongitude" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "plannedStartTime" TEXT NOT NULL DEFAULT '05:00';
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "timePerDropMinutes" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "customerSlotMinutes" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "totalMileage" DOUBLE PRECISION;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "totalDuration" INTEGER;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "notificationsSent" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Route" ALTER COLUMN "plannedStartTime" SET DEFAULT '05:00';
ALTER TABLE "Route" ALTER COLUMN "timePerDropMinutes" SET DEFAULT 10;
ALTER TABLE "Route" ALTER COLUMN "customerSlotMinutes" SET DEFAULT 60;
ALTER TABLE "Route" ALTER COLUMN "notificationsSent" SET DEFAULT false;

ALTER TABLE "Stop" ADD COLUMN IF NOT EXISTS "isLocked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Stop" ADD COLUMN IF NOT EXISTS "estimatedArrival" TIMESTAMP(3);
ALTER TABLE "Stop" ADD COLUMN IF NOT EXISTS "actualArrival" TIMESTAMP(3);
ALTER TABLE "Stop" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "Stop" ADD COLUMN IF NOT EXISTS "deliveryGroupId" TEXT;
ALTER TABLE "Stop" ALTER COLUMN "isLocked" SET DEFAULT false;
ALTER TABLE "Stop" ALTER COLUMN "status" SET DEFAULT 'PENDING';

ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "manualAddress" TEXT;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "useManualAddress" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "postcode" TEXT;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "addressStatus" TEXT NOT NULL DEFAULT 'NEEDS_LOCATION_CHECK';
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "addressSource" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "addressConfidence" TEXT NOT NULL DEFAULT 'LOW';
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "formattedAddress" TEXT;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "manualPinLatitude" DOUBLE PRECISION;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "manualPinLongitude" DOUBLE PRECISION;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "proofPhotoUrl" TEXT;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "deliveryNote" TEXT;
ALTER TABLE "DeliveryGroup" ADD COLUMN IF NOT EXISTS "safePlaceNote" TEXT;
ALTER TABLE "DeliveryGroup" ALTER COLUMN "useManualAddress" SET DEFAULT false;
ALTER TABLE "DeliveryGroup" ALTER COLUMN "addressStatus" SET DEFAULT 'NEEDS_LOCATION_CHECK';
ALTER TABLE "DeliveryGroup" ALTER COLUMN "addressSource" SET DEFAULT 'none';
ALTER TABLE "DeliveryGroup" ALTER COLUMN "addressConfidence" SET DEFAULT 'LOW';

ALTER TABLE "OrderStop" ADD COLUMN IF NOT EXISTS "orderSource" TEXT NOT NULL DEFAULT 'shopify';
ALTER TABLE "OrderStop" ADD COLUMN IF NOT EXISTS "customerEmail" TEXT;
ALTER TABLE "OrderStop" ADD COLUMN IF NOT EXISTS "customerPhone" TEXT;
ALTER TABLE "OrderStop" ADD COLUMN IF NOT EXISTS "postcode" TEXT;
ALTER TABLE "OrderStop" ADD COLUMN IF NOT EXISTS "lineItemSummary" TEXT;
ALTER TABLE "OrderStop" ALTER COLUMN "orderSource" SET DEFAULT 'shopify';

CREATE TABLE IF NOT EXISTS "RouteHistory" (
  "id" TEXT NOT NULL,
  "routeId" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "details" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RouteHistory_pkey" PRIMARY KEY ("id")
);

DO $$
BEGIN
  ALTER TABLE "RouteHistory"
    ADD CONSTRAINT "RouteHistory_routeId_fkey"
    FOREIGN KEY ("routeId") REFERENCES "Route"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "Route"
    ADD CONSTRAINT "Route_driverAccessToken_key"
    UNIQUE ("driverAccessToken");
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
